version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:274201610284:task-definition/users-authentication:1"
        LoadBalancerInfo:
          ContainerName: "process-pension"
          ContainerPort: "8056"
        PlatformVersion: "LATEST"